name:
  - CE_accretors
channels:
  - defaults
dependencies:
  - numpy>=1.20
  - scipy=1.7.1
  - pip>=20.3.3
  - python=3.9
  - pip:
      - matplotlib>=3.4.3
      - git+https://github.com/mathren/compare_workdir_MESA/
